forms/app.py
forms/settings.py

https://assembly.com/formspree/bounties/5
---
Sendgrid [doesn't support sending from our own domain](https://sendgrid.com/docs/User_Guide/whitelabel_wizard.html) for accounts lower than the Silver plan, so we can use the `DEFAULT_SENDER` we're already using and no DNS configurations have to take place now, the problem is that the emails will be sent in fact with a sendgrid domain as the original verified sender and Gmail (maybe others) will display our emails with a nice `via sendgrid.info`.
For generating an API user and key, go to https://sendgrid.com/credentials

use sendgrid for sending emails

---

formspree/settings.py

Adds the `LOG_LEVEL` setting to `settings.py`.
Set from an environment variable named `LOG_LEVEL` and with a default value of `debug`.

Bounty #18: Add Log Level to settings

---

formspree/app.py
formspree/forms/models.py
formspree/settings.py
formspree/static_pages/views.py
manage.py
requirements.txt
tests/formspree_test_case.py
tests/test_form_posts.py

I wanted to get a more standard test runner. Now you can run `python -m unittest discover` to kickoff all tests located in the tests folder. New files with the name test_xxx.py can be included in the tests folder, including subclasses of FormspreeTestCase, that will be run automatically.

Testing refactor

---

.travis.yml

Integrate with Travis to run our tests, so we can have a CI. Later we can pick multiple versions of Python or third-party-libraries to test so we don't have to. :smile_cat:

Enable travis integration

---

formspree/app.py
formspree/templates/email/form.html

What happens today when we send HTML or indented text with Formspree:
What happens after this commit:

send form data inside a <pre> instead of using |nl2br|safe.

---

formspree/templates/static_pages/index.html

Reduce user confusion that Formspree is shutting down by replacing dead links to Assembly with GitHub links

Assembly to GitHub

---

formspree/settings.py
formspree/templates/email/form.html
formspree/templates/email/form.txt
formspree/templates/static_pages/index.html

this does not work.
`current_user` is the logged user, but we should be checking for the user who owns the form being submitted.

Revert "Publicize formspree gold info"

---

formspree/forms/models.py
formspree/utils.py

@fiatjaf This should allow for us to see the actual error code that SendGrid is providing, as well as the error message. Before it was only returning a general failure code if SendGrid returned anything other than a 200 response.

Better SendGrid error messaging

---

formspree/forms/models.py
formspree/forms/views.py
formspree/templates/email/confirm.html
formspree/templates/email/confirm.txt
formspree/templates/email/form.html

As suggested [here](https://trello.com/c/CzyN0Y8M/1138-storing-submissions-before-email-verification).
I have zero design skills, but anyway I had to accommodate the form contents inside the confirmation email, so I made some small changes:
Please make corrections and suggestions.

Send first form submission along with confirmation email

---

formspree/forms/views.py
formspree/templates/forms/list.html

helps users identify which forms were created automatically by a submission and which were created from the dashboard, in case there are many with the same URL-email combination.

show hint with the actual url that is being or must be used for each form.

---

formspree/forms/models.py
formspree/forms/views.py
formspree/utils.py
tests/formspree_test_case.py
tests/test_content_types.py

This is a dumb implementation I came up with. It seems to work whenever I test it (after I fixed various quirks and bugs), but there's probably some bug still. Anyway, the present request_wants_json, however, is not foolproof, it is failing and must be changed.
Most Javascript HTTP libraries, superagent, for example, automatically send the data you pass to them in JSON format and set the Content-Type header to application/json, but don't set the Accept header. And I can't imagine a situation in which someone would send an AJAX request like this and expect an HTML response.
Also, Angular automatically sets the Accept header to application/json, text/plain, */*, and I don't know why but Werkzeug parses it in a way that request.accept_mimetypes['application/json'] is 1, but …

make API much more flexible with different types of incoming requests

---

formspree/templates/static_pages/index.html

Added a new step, also a notice about multiple URLs.
Is this too big or too verbose? Should I mix the step 2 in the 1? Or remove the step 4?

More begginer setup instructions on the home page

---

formspree/forms/views.py
formspree/templates/forms/confirmation_sent.html

If, at the time the user tries to resend the confirmation, we detect that his first confirmation email has bounced, a screen like this is shown:
Then, after he goes to his mailbox and verify everything, he comes back and tries to resend confirmation again, then he is presented with the same resend-confirmation + recaptcha screen, however this time there's a checkbox that he can check and confirm that he has verified his mailbox.
The checkbox is shown to whatever user has the cookies that say he has seen the bounce message (first image). The cookie lasts for 4 days. If the checkbox is checked, the server automatically drops the bounce from SendGrid using their API and tries to resend the confirmation.
This removes a lot of the work load from the support team.
You can test it by submitting …

automate the bounce deletion process.

---

formspree/static_pages/views.py

Some users were having the issue where https://formspree.io/favicon.ico redirects to http://formspree.io/static/img/favicon.ico, which caused Chrome to say our website was insecure. This should tell Flask that it should get the favicon from the SSL version

Fix unsecured favicon on the homepage

---

formspree/routes.py
formspree/templates/email/pre_inline_style/email_styles.css
formspree/templates/email/pre_inline_style/reset-password.html
formspree/templates/email/reset-password.html
formspree/templates/email/reset-password.txt
formspree/templates/email/text_form.html
formspree/templates/layouts/base.html
formspree/templates/static_pages/index.html
formspree/templates/users/forgot.html
formspree/templates/users/login.html
formspree/templates/users/reset.html
formspree/users/models.py
formspree/users/views.py
tests/test_users.py

**Adds a missing basic feature we should have always had.**
* Adds a link to the `/login` screen for users who forgot their passwords.
* Generates an HMAC token and sends for the user based on the email he has inputted.
* The token is valid eternally as long as the password doesn't change. If the token is never clicked, never happens. Even if it is clicked, but the user gives up completing the password change process, never happens, the old password is still valid.
I'll have a working demo soon, but there are two new screens, one just for inputting the email for which the password will be resetted, and other for inputting the new password (twice). They are exactly the same as the `/login` …

Password reset with email.

---

formspree/forms/helpers.py
formspree/forms/models.py
formspree/templates/static_pages/index.html
formspree/utils.py

**New feature**
* Allow for a user to include multiple _cc email addresses by allowing for a list of emails separate by comma
* Also allow for same functionality with BCC
No tests for _cc exist currently, but maybe some should be added. It is just a standard feature in the SendGrid API though.
None necessary
Not sure if adding the BCC field is too many options, but it might be nice if people want to receive a copy of submissions.

Multiple cc

---

.gitignore
formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/static/css/main.css
formspree/static/js/bundle.js
formspree/static/js/main.js
formspree/static/scss/dashboard.scss
formspree/static/scss/main.scss
formspree/templates/forms/create.html
formspree/templates/forms/list.html
formspree/templates/forms/submissions.html
formspree/templates/layouts/base.html
formspree/templates/static_pages/index.html
formspree/templates/users/dashboard.html
formspree/utils.py
migrations/versions/ee9b6bc06d8a_sitewide_forms.py
package.json
requirements.txt
tests/test_form_creation.py
tests/test_users.py

**New feature**
* The form creation API now supports creating forms that are pre-confirmed if the target email was already verified for the user account.
* The form creation API now supports creating forms verified site-wide. At the moment of the form creation an HTTP request is made to check for the presence of a verification file at the root path of the site that is being authorized.
* Adds a new boolean column to the `forms` table, named "sitewide".
**Demo**
http://formspree-fiatjaf.herokuapp.com/ (say your registered email there if you want a Gold account to test)
Database migration: `heroku run python manage.py db upgrade --app formspree-asm`

Site-wide confirmations

---

README.md
formspree/templates/static_pages/index.html
formspree/templates/users/dashboard.html

As [Paul Irish put it](https://twitter.com/paul_irish/status/588502455530311680):
> The protocol relative URL is now an anti-pattern. If the asset is available on HTTPS, always request it with that. https://www.paulirish.com/2010/the-protocol-relative-url/
This ensures that forms are always submitted using HTTPS, even on websites delivered by HTTP.
-----
**Fixes partially #85.**
* Drop the use of the protocol-relative URL (`//host/...`) in favor of always using HTTPS (`https://host/...`).
* Change the home page URL to HTTPS.
* Change the `API_ROOT` config variable: now it must begin with `https://`.
See website screenshots over at https://github.com/formspree/formspree/issues/85#issuecomment-197026612. …

Use https in documentation

---

formspree/forms/views.py

It happens that there's another situation in which no Referrer header is found besides people browsing HTML files on their computers: when an HTTPS site tries to submit to an HTTP site.

alert for https when no Referer header was found.

---

.gitignore
formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/static/css/main.css
formspree/static/js/bundle.js
formspree/static/js/main.js
formspree/static/js/sitewide.js
formspree/static/scss/dashboard.scss
formspree/static/scss/main.scss
formspree/templates/forms/create.html
formspree/templates/forms/list-item.html
formspree/templates/forms/list.html
formspree/templates/forms/submissions.html
manage.py
package.json
tests/test_form_creation.py
tests/test_users.py

**Fixes issues raised by @colevscode on the poor state of the form creation modal**
* Changes the verification method from checking for a file like `/formspree_verify_email@address.com.txt` to checking for a file like `/formspree-verify.txt` with email addresses listed inside (newline separated)
* Adds virtual-dom dependency for handling the multiple states of the form creation modal in a sane way
* Makes pure-CSS JS-enhanced modals fully-functional back again by checking triggering modals from JS based on the URL has (`#`)
* Change a little bit of everything in the layout, colours and display of forms list
* Changes modal with example form HTML to be copied and pasted from a black-and-white HTML form with 3 standard `<input>` fields to a …

Fix form creation modal

---

formspree/templates/email/form.html
formspree/templates/email/pre_inline_style/form.html

**Fixes #92.**
* Support for multiple lines inside an email body
(None necessary)
No changes necessary.

Support multiple lines inside an email body

---

formspree/app.py
formspree/helpers.py
formspree/settings.py
tests/formspree_test_case.py

**Fixes #85.**
* Forward GET requests over HTTP to redirect to HTTPS
* Do **NOT** forward POST requests sent over HTTP to be redirected to HTTPS. This is because this would require using the 307 status code, which has unknown implementation on older browsers. Additionally, any POST requests sent over HTTP would have already exposed sensitive information unencrypted, rendering the useless, only causing additional server load. #86 does encourage users to use the HTTPS URL going forward
None necessary

Redirect to HTTPS

---

formspree/forms/models.py
formspree/forms/views.py
formspree/utils.py
tests/test_form_posts.py

Implements https://trello.com/c/gJ2EtOYF/3206-validate-replyto-field-reject-invalid-email-addresses
* When the `_replyto` or `email` field does not match the email regex, reject the submission and show an error message.
**Screenshot**

reject form submission when _replyto does not validate.

---

formspree/settings.py
formspree/templates/static_pages/index.html

* Replaces test form at bottom of page with newsletter signup form. 
* Adds newletter email to settings
The intention with this change is to use a parser.zaper.com email address, and then create a zap that wires up the email submissions to mailchimp.
I should merge this so that I can quickly configure the zapier / mailchimp integration.

replacing contact form with a newsletter signup

---

formspree/forms/helpers.py
formspree/forms/views.py
formspree/templates/layouts/base.html
formspree/users/models.py
formspree/users/views.py
tests/test_email_confirmations.py
tests/test_form_creation.py

**Fixes https://trello.com/c/qsGeTz2m/4727-support-unicode-emails and many other occurrences.**
* Uses unicode objects in `flash` messages and manually-built HTML.
* In some places (3, I think) manually encode email addresses to UTF-8.
* Reformat some lines of code where strings were too big, chunking them to multiple lines. This is not related to the functionality, but since I was already messing with these lines I thought it would be a good thing.
The "tests" here are just some random changes in email addresses used in existing tests that I've changed to unicode strings with non-ascii characters.
Nothing.
Just using u'unicode' in all the arbitrary strings built by …

Support unicode emails.

---

formspree/templates/email/form.html
formspree/templates/email/plain_form.html

Long strings of text were causing display issues in several email clients (see screenshots below for examples). This is due to the default line wrapping behavior of the `<pre>` tags which hold the form field values. This does not seem to be affecting short text strings (I noticed the issue with ~1000 characters from a `<textarea>` element). This affects both the HTML and plain versions of the email, since both versions are using `<pre>` tags. The following email clients had display issues (tested in Litmus):
* Apple Mail 9 & 10
* Outlook 2000-2003, 2011, 2016
* AOL Mail
* Inbox by Gmail
* Office 365
* Outlook.com
I fixed this by adding `white-space: pre-wrap;` to the inline styles on the `<pre>` tags. This keeps the original white space …

Fix several display issues with long text in <pre> tag

---

formspree/templates/static_pages/index.html

Based on https://trello.com/c/AIN5tAkT
The link is http://help.formspree.io/
I've also moved the "managed on GitHub" part to the bottom of the page. I didn't know what to do to shorten that paragraph, but this seemed a good solution since there is already a mention of the GitHub repo and organization on the "Questions" section above.

add knowledge base link to home page.

---

formspree/app.py

**Fixes https://trello.com/c/muk9EBuA**
* Removed code that sent `Strict-Transport-Security` header.
HSTS doesn't seem to work well for Formspree.
Copy-pasted from https://trello.com/c/muk9EBuA#comment-583f518d568f990567511af4:
> [This code here](https://github.com/formspree/formspree/blob/246efe60e07f1a24c93f187f6a2b7e1a1ab0239c/formspree/app.py#L50-L51) is setting an HSTS policy on the browsers of everybody who visits https://formspree.io/.
> 
> I didn't know what was HSTS until now.
> 
> Later, when that same user tries to submit a form from another page, if the `action` attribute is set to `http://formspr...` the browser will perform an 307 INTERNAL REDIRECT by itself, without touching the server, and then …

do not send Strict-Transport-Security header.

---

formspree/forms/models.py
formspree/forms/views.py
formspree/templates/forms/captcha.html

**Fixes https://trello.com/c/8LfbNMlT**
* The sorted `keys` extracted from Flask's `request.form` is now passed to `captcha.html` so the data is rendered in that page in the same order they were submitted at first.

preserve keys order through captcha page.

---

formspree/static/css/main.css
formspree/static/scss/dashboard.scss
formspree/static/scss/grid.scss
formspree/static/scss/main.scss
formspree/templates/forms/captcha.html
formspree/templates/forms/confirmation_sent.html
formspree/templates/forms/submissions.html
formspree/templates/forms/unblock_email.html
formspree/templates/layouts/base.html
formspree/templates/layouts/message.html
web/test2.html

Cleaning up styles, removing menu on message screens.
Currently the experience on mobile is pretty bad. This cleans up a lot of stuff. Also I felt that when visiting the thanks, and other pages, the menu was overbearing. Removing that gives a clean look to our captcha and thanks pages, especially on mobile. Since everyone sees these now, this is important. The link to the formspree homepage still is visible below the card.
* Removing menu bar on message screens (confirmation, thanks, captcha)
* General cleanup of mobile
* tweaks to the submissions page.

cleaning up css styles for mobile. Removing menu on confirmation

---

formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/static/css/main.css
formspree/static/js/captcha-toggle.js
formspree/static/scss/main.scss
formspree/templates/forms/submissions.html
formspree/templates/static_pages/index.html
tests/test_form_creation.py

* Allow Gold users to toggle the CAPTCHA on their forms
* Make sure that only Gold users can have a disabled CAPTCHA
No DB migrations necessary. Was already completed in #133.

Captcha toggle

---

formspree/templates/forms/captcha.html

Solves the formatting problem caused by the fact that browsers ignore newlines when they are part of the value of `<input>` fields (but not when they're in `<textarea>` fields).
**Fixes https://trello.com/c/7OOql9ny**
* Replace **all** `<input>` fields generated in `formspree/templates/forms/captcha.html` to accomodate the user submitted data with `<textarea>` fields, no matter how this data was first submitted.
Nothing.

textarea fields in recaptcha page.

---

formspree/routes.py
formspree/templates/users/account.html

**Fixes resubscription not working.**
* Resubscription button was pointing to wrong URL route
None necessary. Simple but important fix.

Fixed url routing for resubscription

---

formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py
tests/test_form_posts.py

This is a possible way to solve the problems of users who set up Formspree and forget to test them (because they are already familiar with Formspree, probably) and end up missing their first submission. I've done that myself, we've experimented it with Formspree's own forms. It's a problem.
This PR just introduces code that saves the data, unordered, unfiltered, on Redis upon the first submission -- only the first -- of a form that would trigger sending an email confirmation. The data on Redis is set to expire in some days.
When the form is confirmed, that data is just fetched and emailed just like a normal form submission would be.

store first submission on redis, send it on confirmation.

---

formspree/templates/forms/captcha.html

**Fixes error when reloading reCAPTCHA page.**
* Store the data in session storage on reCAPTCHA page to prevent empty data.
None.
None necessary.
Currently, if the user has the HSTS policy set on their browser, if they submit to the HTTP version of Formspree and reload the reCAPTCHA page, it loses the data. A very niche scenario, but operating under the assumption that the HSTS is set for our users, this will store the data in [session storage](https://developer.mozilla.org/en/docs/Web/API/Window/sessionStorage). Upon loading, it will check if data exists in session storage. Right before submitting, it will remove the data from session storage.

Store data in session storage for reloading page

---

formspree/forms/helpers.py
formspree/forms/views.py
formspree/templates/forms/captcha.html
formspree/templates/forms/captcha_lang/en.html
formspree/templates/forms/captcha_lang/es.html
formspree/templates/forms/captcha_lang/pt.html
formspree/templates/static_pages/index.html

**Fixes internationalization issues.**
* Add Spanish as a supported language for reCAPTCHA using _language variable
None necessary.
Address user complaints about displaying Formspree reCAPTCHA in their native language. Very simple and easy to add new languages.

Captcha internationalization

---

formspree/forms/views.py

**Fixes https://formspree.zendesk.com/agent/tickets/5**
* Discard ending slashes when setting and when comparing stored `.host` values with the host that has actually submitted the form. Since forms created through the dashboard have an id and the submission is identified by it (and not by the host/referrer value) this is safe. The value of `.host` in this case is only used for validation -- while in forms created automatically it is used for identification.
Nothing.

ignore ending slashes for forms created in the dashboard.

---

.gitignore
formspree/forms/models.py
formspree/templates/email/90-percent-warning.html
formspree/templates/email/90-percent-warning.txt
formspree/templates/email/pre_inline_style/90-percent-warning.html

**Send warning when user hits 90% of their form limit**
* When a free tier user is at 90% they will be sent a warning email
None necessary.

90 percent warning

---

formspree/forms/views.py
formspree/utils.py
manage.py
tests/formspree_test_case.py
tests/test_content_types.py
tests/test_form_creation.py
tests/test_form_posts.py

* To combat a spam technique in which attacker sends confirmation emails that appear to come from formspree.io (so appears trusted), then sends spam, we now disallow confirmations from formspree.io.

adding check to ensure referrer hostname doesn't match SERVICE_URL

---

README.md
formspree/forms/views.py
formspree/templates/static_pages/index.html
formspree/templates/users/account.html
tests/test_form_posts.py

* Currently we're seeing a lot of spam come from ajax forms, since we must allow ajax to bypass the CAPTCHA. Unfortunately the most strait forward solution is to remove this capability.
* This PR makes submitting AJAX forms a gold feature.
* Existing forms will continue to work, even AJAX forms that have been created by non gold users.

removing ajax creation for non gold accounts

---

formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py

* Stop storing all the keys in `KEYS_NOT_STORED` that are being currently stored in the `submissions` table.
* Start showing `'_subject'`, `'_cc'` and  `'_next'` in the submissions list on the dashboard, as they may contain useful information for the form owner (do they? I'm personally using `_subject` in one of my forms as the field where the submitter writes his name) -- they still won't be sent in the submission email.

Stop storing useless keys.

---

formspree/templates/email/confirm.html
formspree/templates/email/pre_inline_style/confirm.html

I wanted to implement https://developers.google.com/gmail/markup/reference/one-click-action#confirm_action, but I can't know if it will work.
I guess Gmail only shows actions for some selected senders, right? I couldn't get information on this. Maybe Formspree already applies. Anyway, it would be a nice thing to have, and we just have to include these JSON-LD attributes, everything else is already in place.

Gmail Action for confirm emails.

---

formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/utils.py
tests/test_list_unsubscribe.py

In order to make [Gmail actions](https://github.com/formspree/formspree/pull/171) work we [must](https://support.google.com/mail/answer/81126?hl=en) implement this [List-Unsubscribe](https://www.ietf.org/rfc/rfc2369.txt) thing.
It would actually be a good thing, if it worked as intended (Gmail showing a special "unsubscribe" link, only visible to the first recipient of our email).
Even if it doesn't work, I believe it will do no harm. Email headers are not redirected when someone forwards or replies to an email, so there isn't a problem of third-parties unconfirming a form on behalf of some Formspree user. Also, exposing an `/unconfirm/<digest>/<form_id>` endpoint isn't a problem if the user doesn't know the digest.
I may be missing something. Please let me know.

List-Unsubscribe headers and unconditional form unconfirmation endpoint.

---

formspree/users/views.py

* Previously when a user loged in, if they mistyped their email, it would give them an error. This has been replaced by a generic "username or password" error.
* Previously if a user tried to reset their password, and supplied an incorrect email, they would be notified that the email wasn't in the system. This has been replaced with a generic "check your inbox" message.
* Overall revealing whether an email is in our system provides hackers with more information that they can use to gain unauthorized access.
[Put any changes necessary in order to deploy (such as DB migrations)]

Hiding missed username when logging in

---

formspree/forms/views.py
tests/test_unsubscribe.py

Tries to fix the problem of users with email antivirus that open their URLs (also known as NSA malwares) getting unconfirmation emails along with each submission.

Repel bots on unconfirm URL.
