forms/templates/email/form.html

https://assembly.com/chat/formspree#comment-84

complement <small> with font-size: 10px on email template

---

forms/__init__.py
forms/app.py

* made `nl2br` lambda-form
* avoid assigning `settings.DEFAULT_SENDER` to a new variable
* use `Flask(__name__)` for better debugging
* add a conditional `app.run(host='0.0.0.0')` for debugging

some harmless changes/cleanups

---

manage.py

see https://assembly.com/formspree/bounties/13#460a077d-8135-4f65-ae54-636d890860bd

added redis->postgres migration script

---

forms/app.py
requirements.txt

see https://assembly.com/formspree/bounties/13#460a077d-8135-4f65-ae54-636d890860bd

app code with sqlalchemy in place of redis

---

formspree/static/css/main.css
formspree/static/scss/main.scss
formspree/templates/users/login.html
formspree/templates/users/register.html

This is for bounty #19. Cleaning up some copy, HTML & CSS on the log in and register pages.
One note, would be the urls. Not sure if we have a reverse url router for the templates or not.

tidy up login/registration panels

---

.gitignore
formspree/forms/helpers.py
formspree/settings.py
formspree/tests/FormPosts.py
manage.py
requirements.txt

This is for bounty 16; including a simple framework for testing the form creation and activation flow.

Testing Framework

---

README.md

I've just tried to run the project on my local and I used the experience to update the development docs.

Update development instructions.

---

formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/users/views.py
formspree/utils.py
tests/test_users.py

https://assembly.com/formspree/bounties/15

Form creation API

---

formspree/app.py
formspree/forms/models.py
formspree/forms/views.py
formspree/routes.py
formspree/users/views.py
formspree/utils.py
tests/test_users.py

Made a few adjustments to your pull request (https://github.com/asm-products/formspree/pull/23). Moved the form api into the form module. I think it belongs there. Just because it requires user authentication doesn't mean that its not a form api endpoint. Also cleaned up a few things.
//Cole

forms api merge

---

README.md
formspree/forms/helpers.py
formspree/forms/models.py
formspree/settings.py
formspree/utils.py
requirements.txt
tests/test_users.py

http://hashids.org/
salted hashids with a custom alphabet, in fact, with a salt specified at the HASHIDS_SALT environment variable.

replace int2bigstring and bigstring2int with hashids

---

formspree/templates/static_pages/index.html

Simple addition just a link to contact e-mail.
I just closed/re-opened this PR so Travis CI re-run the tests (they failed for some random reason not test related).

Add link to contact e-mail

---

README.md

There is a really small typo in the README.md file.

Fixing a typo.

---

formspree/forms/views.py
formspree/routes.py
formspree/templates/forms/list.html
formspree/templates/forms/submissions.html
requirements.txt
tests/test_archive_submissions.py

I don't know if this is useful, but I imagine non-dev people like to have an option to export things to files.

buttons for manually exporting submissions to csv or json

---

formspree/settings.py
formspree/templates/email/form.html
formspree/templates/email/form.txt
formspree/templates/static_pages/index.html

Users will now see a link to upgrade to formspree gold on every form submission they receive

Publicize formspree gold info

---

README.md
formspree/users/views.py

Passing email address in the alert message

Passing email address in the alert message

---

formspree/templates/static_pages/index.html

* some modifications based on users requesting help behavior.
* update repo from asm-products to formspree.

add a little info to landing page.

---

formspree/forms/models.py
formspree/forms/views.py

Addressing issue where people have multiple _replyto fields

Display error message for SendGrid 400 error

---

formspree/forms/models.py
formspree/forms/views.py
formspree/utils.py
tests/formspree_test_case.py
tests/test_content_types.py

Commits from @fiatjaf to fix the API issue

Added @fiatjaf commits to be merged

---

formspree/templates/email/confirm.html

I didn't know it was possible to open PRs to branches.

added a missing }

---

formspree/utils.py

Enables cc'ing without requiring the reply_to field.

Remove reply_to dependency for _cc

---

formspree/forms/views.py

I don't remember why I did this, but I had forgotten to commit and push it. It was probably because some user had reported having the same email address with different cases being treated as different addresses.
I just want to make sure I'm not missing anything.

lowercase all emails.

---

formspree/templates/static_pages/index.html

* improving _format example on front page.

improving _format example

---

formspree/static/css/main.css
formspree/static/scss/dashboard.scss
formspree/templates/forms/list-item.html
formspree/templates/forms/list.html
formspree/templates/forms/submissions.html

**Fixes https://trello.com/c/FCYdQLFL and other small things**
* Add a `ridge` border to the submissions table `td`s.
* Make the submissions table horizontally scrollable -- instead of allowing free overflow -- when there are too many fields.
* Submissions values `td`s are limited to 300px.
* Long submission values are truncated to 270 characters, with a link to display the entire value (and a link to hide the entire value when it is shown) (pure HTML, no JS).
* Submissions and forms tables rows are turned into "stacks" on screens smaller than 600px (pure CSS).

Table formatting

---

formspree/templates/email/form.html
formspree/templates/email/plain_form.html
formspree/templates/email/pre_inline_style/form.html

This is almost a mirror of https://github.com/formspree/formspree/pull/124.

Fix several display issues with long text in <pre> tag

---

.travis.yml
formspree/forms/helpers.py
formspree/forms/models.py
formspree/forms/views.py
formspree/settings.py
formspree/templates/forms/captcha.html
formspree/templates/layouts/base.html
formspree/utils.py
manage.py
web/test-heroku.html
web/test.html
web/thanks.html

**Fixes # .**
* Adding captcha interstitial screen after each submission
No db migrations required. Makes use of redis to store referrer info from original submission to pass it through to request generated from captcha page.

Withcaptcha

---

formspree/forms/views.py
formspree/templates/forms/captcha.html

* Make Gold forms use a CAPTCHA by default
* Fix the bug when users have an input field where `name="submit"`
None

Some CAPTCHA Fixes

---

formspree/forms/views.py

we may or may not use this data later.

start tracking which forms use mostly ajax as of today.

---

formspree/forms/views.py

**Fixes bug in #137.**
* Fix logic error with CAPTCHA disabling for free users
Urgent fix, deploying immediately

Logic error in form disabling

---

formspree/static/css/main.css
formspree/static/js/captcha-toggle.js
formspree/static/scss/dashboard.scss
formspree/templates/forms/list.html
formspree/templates/forms/submissions.html

**Fixes issues raised by @colevscode in #137.**
* Move reCAPTCHA toggle from submissions page to form modal
* Fixed HTML indentation
* Spelling fix
None necessary, all changes are front end

Move CAPTCHA to forms list and clean up styles

---

formspree/forms/views.py
formspree/templates/forms/thanks.html
formspree/utils.py
tests/test_form_posts.py

**Fixes 5f18eea.**
* Ensure that if a user externally links to Formspree thanks page, no XSS vulnerability is possible

Prevent XSS Vulnerability on "Return to Site" Button

---

formspree/templates/forms/thanks.html
formspree/utils.py
tests/test_form_posts.py

**Fixes #174.**
* Discovered in staging that XSS fix didn't work, so haven't deployed into prod

Better Fix for XSS

---

formspree/users/views.py
formspree/utils.py

* Upon user creation, record the user's IP address
* Upon user login from a new device, record user's IP address
None necessary.

Add ip logging for user events

---

formspree/templates/forms/captcha_lang/ca.html

add Catalan language to captcha form
**Fixes # .**
* [Change 1]
* [Change 2]
* [Other changes...]
[Insert screenshot or GIFs of old and new behavior]
[Put any changes necessary in order to deploy (such as DB migrations)]

add Catalan translation

---

.gitignore
formspree/static/css/main.css
formspree/static/scss/main.scss
formspree/static/scss/typography.scss
formspree/templates/layouts/base.html
formspree/templates/static_pages/index.html

* Adds better Title, Description and H1 / H2 content for SEO
* Moves previous H1 / H2 content to P tags, and uses "seo-hack" classes to maintain styles

improved on-page SEO

---

.gitignore
Pipfile
Pipfile.lock
Procfile
formspree/__init__.py
formspree/create_app.py
formspree/manage.py
formspree/templates/email/downgraded_reason.txt
formspree/templates/users/billing.html
formspree/users/helpers.py
formspree/users/views.py

See #196 
This is just a duplicate of that PR.

Downgrade reason

---

formspree/forms/endpoint.py
formspree/forms/errors.py
formspree/forms/views.py
formspree/routes.py

* refactor to the send() function in forms/views.py. Split it out into its own endpoint.py file and pulled out error responses into an errors.py file. 
I've tested thoroughly so we should be OK to merge, but might want to keep an eye on things...

Refactor endpoint

---

formspree/templates/forms/captcha_lang/hr.html

* added HR (Croatian) variant of CAPTCHA template form

Added HR (Croatian) captcha template variant
